name = "PoingrSimulator"
uuid = "01eb3d57-6371-4320-8e81-081701a85da1"
authors = ["Keita Nakamura <keita.nakamura.1109@gmail.com>"]
version = "0.10.1"

[deps]
GeometricObjects = "f167b195-1c3d-409a-8dd6-02cc02a656c6"
Poingr = "573615e8-489b-4e48-952b-fc194aa7573b"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
GeometricObjects = "0.5"
Poingr = "0.20"
UnicodePlots = "1, 2"
julia = "1.6"
